package org.fabric3.tests.binding.metro.upload;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.0_03-b24-fcs Generated source version: 2.0
 */
@WebService(name = "UploadPortType", targetNamespace = "urn:upload")
public interface UploadPortType {

    @WebMethod
    @WebResult(name = "size", targetNamespace = "urn:upload")
    @RequestWrapper(localName = "upload", targetNamespace = "urn:upload", className = "upload.UploadType")
    @ResponseWrapper(localName = "uploadOut", targetNamespace = "urn:upload", className = "upload.UploadResponseType")
    public int upload(
            @WebParam(name = "name", targetNamespace = "urn:upload")
            String name,
            @WebParam(name = "data", targetNamespace = "urn:upload")
            DataHandler data);

}
