<?xml version="1.0" encoding="UTF-8"?>

<definitions name="AddNumbers" targetNamespace="urn:addnumbers"
	xmlns:tns="urn:addnumbers" xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<message name="addRequest">
		<part name="arg1" type="xsd:int" />
		<part name="arg2" type="xsd:int" />
	</message>
	<message name="addResponse">
		<part name="result" type="xsd:int" />
	</message>

	<portType name="AddNumbersPortType">
		<operation name="addNumbers">
			<input message="tns:addRequest" />
			<output message="tns:addResponse" />
		</operation>
	</portType>

	<binding xmlns:ns1="urn:addnumbers"
		name="AddNumbersBinding" type="ns1:AddNumbersPortType">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="rpc" />
		<operation name="addNumbers">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<service name="AddNumbersService">
		<port name="AddNumbersPort" binding="tns:AddNumbersBinding">
			<soap:address location="REPLACE_WITH_ACTUAL_URL" />
		</port>
	</service>

</definitions>