
package org.fabric3.tests.wsdl.matching.multielementcomplextype;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWorldPortType", targetNamespace = "urn:helloworld:mect")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldPortType {


    /**
     * 
     * @param sessionid
     * @param name
     * @return
     *     returns test.wsdl.matching.multielementcomplextype.SayHelloResponseType
     */
    @WebMethod
    @WebResult(name = "sayHelloResponse", targetNamespace = "urn:helloworld:mect", partName = "result")
    public SayHelloResponseType sayHello(
        @WebParam(name = "sessionid", targetNamespace = "urn:helloworld:mect", header = true, partName = "sessionid")
        String sessionid,
        @WebParam(name = "sayHelloRequest", targetNamespace = "urn:helloworld:mect", partName = "name")
        SayHelloRequestType name);

}
