package org.fabric3.tests.wsdl.matching.singlecomplextype;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWorldPortType", targetNamespace = "urn:helloworld:sct")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldPortType {


    /**
     * 
     * @param name
     * @return
     *     returns test.wsdl.matching.singlecomplextype.SayHelloResponse
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public SayHelloResponse sayHello(
        @WebParam(name = "name", partName = "name")
        SayHelloRequest name);

}
