
package org.fabric3.tests.wsdl.matching.multicomplextype;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AddNumbersPortType", targetNamespace = "urn:addnumbers:mct")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddNumbersPortType {


    /**
     * 
     * @param arg1
     * @param arg2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public int addNumbers(
        @WebParam(name = "arg1", partName = "arg1")
        AddNumbersType arg1,
        @WebParam(name = "arg2", partName = "arg2")
        AddNumbersType arg2);

}
