package org.fabric3.tests.binding.metro.helloworld;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.1 in JDK 6 Generated source version: 2.1
 */
@WebFault(name = "helloFault", targetNamespace = "urn:helloworld")
public class HelloFaultException
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private HelloFault faultInfo;

    /**
     * @param message
     * @param faultInfo
     */
    public HelloFaultException(String message, HelloFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param message
     * @param faultInfo
     * @param cause
     */
    public HelloFaultException(String message, HelloFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: helloworld.HelloFault
     */
    public HelloFault getFaultInfo() {
        return faultInfo;
    }

}
