
package org.fabric3.tests.binding.metro.helloworld;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorldService", targetNamespace = "urn:helloworld", wsdlLocation = "file:/Users/jim/workspace/fabric3/codehaus/fabric3/tests/trunk/test-binding-metro/src/main/resources/HelloWorld.wsdl")
public class HelloWorldService
    extends Service
{

    private final static URL HELLOWORLDSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/Users/jim/workspace/fabric3/codehaus/fabric3/tests/trunk/test-binding-metro/src/main/resources/HelloWorld.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HELLOWORLDSERVICE_WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(HELLOWORLDSERVICE_WSDL_LOCATION, new QName("urn:helloworld", "HelloWorldService"));
    }

    /**
     * 
     * @return
     *     returns HelloWorldPortType
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorldPortType getHelloWorldPort() {
        return (HelloWorldPortType)super.getPort(new QName("urn:helloworld", "HelloWorldPort"), HelloWorldPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldPortType
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorldPortType getHelloWorldPort(WebServiceFeature... features) {
        return (HelloWorldPortType)super.getPort(new QName("urn:helloworld", "HelloWorldPort"), HelloWorldPortType.class, features);
    }

}
