package org.drools.examples.helloworld
 
import org.fabric3.tests.drools.message.HelloMessage;

rule "Hello World"
    dialect "mvel"
    when
        m : HelloMessage( status == HelloMessage.HELLO, message : message )
    then
        ;
    modify ( m ) { message = "Goodbye cruel world",
                   status = HelloMessage.GOODBYE };
end

rule "Good Bye"
    dialect "java"
    when
        HelloMessage( status == HelloMessage.GOODBYE, message : message )
    then
       ;
end
