
package org.fabric3.tests.standalone.cluster.bindingsca.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TestClientService", targetNamespace = "http://app1.bindingsca.cluster.standalone.tests.fabric3.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestClientService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invoke", targetNamespace = "http://app1.bindingsca.cluster.standalone.tests.fabric3.org/", className = "org.fabric3.tests.standalone.cluster.bindingsca.client.Invoke")
    @ResponseWrapper(localName = "invokeResponse", targetNamespace = "http://app1.bindingsca.cluster.standalone.tests.fabric3.org/", className = "org.fabric3.tests.standalone.cluster.bindingsca.client.InvokeResponse")
    public String invoke(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
