package org.fabric3.tests.wsdl.matching.singlesimpletype;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWorldPortType", targetNamespace = "urn:helloworld:sst")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorldPortType {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String sayHello(
        @WebParam(name = "name", partName = "name")
        String name);

}
