package org.fabric3.tests.wsdl.matching.multisimpletype;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AddNumbersService", targetNamespace = "urn:addnumbers:mst", wsdlLocation = "file:/C:/F3Development/test/test-wsdl-matching/wsdl/MultiSimpleType.wsdl")
public class AddNumbersService
    extends Service
{

    private final static URL ADDNUMBERSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.fabric3.tests.wsdl.matching.multisimpletype.AddNumbersService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.fabric3.tests.wsdl.matching.multisimpletype.AddNumbersService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/F3Development/test/test-wsdl-matching/wsdl/MultiSimpleType.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/F3Development/test/test-wsdl-matching/wsdl/MultiSimpleType.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ADDNUMBERSSERVICE_WSDL_LOCATION = url;
    }

    public AddNumbersService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddNumbersService() {
        super(ADDNUMBERSSERVICE_WSDL_LOCATION, new QName("urn:addnumbers", "AddNumbersService"));
    }

    /**
     * 
     * @return
     *     returns AddNumbersPortType
     */
    @WebEndpoint(name = "AddNumbersPort")
    public AddNumbersPortType getAddNumbersPort() {
        return super.getPort(new QName("urn:addnumbers", "AddNumbersPort"), AddNumbersPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddNumbersPortType
     */
    @WebEndpoint(name = "AddNumbersPort")
    public AddNumbersPortType getAddNumbersPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:addnumbers", "AddNumbersPort"), AddNumbersPortType.class, features);
    }

}
